apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Lucasnobrepro/airflow.git'
    targetRevision: main
    path: charts/argo-cd/argocd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true